version: '3'
services:

  nginx:
    image: 'nginx:latest'
    ports:
      - "80:80"
    volumes:
      - ./hosts/default:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./logs:/var/log/nginx
    networks:
      - app_net

  php:    
    build: ./images/php
    volumes:
      - ./www:/var/www
    networks:
      - app_net

  mysql:
    container_name: mysql
    image: mariadb
    command: mysqld --default-authentication-plugin=mysql_native_password
    #ports:
      #- "3307:3306"
    volumes:
      - ./mysql/DB:/var/lib/mysql
      - ./mysql/.my.cnf/:/root/.my.cnf
    env_file: .env
    networks:
      - app_net

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
       - 8183:80
    env_file: .env  
    networks:
      - app_net

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.172.170.0/24"
